version: '3.8'

services:
  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgresdb
      - redis
    env_file:
      - .env.dev
    restart: always

  redis:
    image: redis:7.0-alpine
    env_file:
      - .env.dev
    volumes:
      - ./redis_data:/data
    restart: on-failure
    ports:
      - "6377:6379"

  postgresdb:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5437:5432"